name: Frontend CD

on:
  push:
    branches: [ master ]
    paths:
      - "starter/frontend/**"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPO: 123162308440.dkr.ecr.us-east-1.amazonaws.com/frontend
  REACT_APP_MOVIE_API_URL: http://af251049516fd4d1d8131efe04876ee5-2112197463.us-east-1.elb.amazonaws.com
  EKS_CLUSTER_NAME: cluster

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: CI=true npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

      - name: Build Docker image
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL \
            -t frontend:${{ github.sha }} \
            -t $ECR_REPO:${{ github.sha }} \
            ./starter/frontend

      - name: Push Docker image to ECR
        run: docker push $ECR_REPO:${{ github.sha }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Set image tag with kustomize
        working-directory: starter/frontend/k8s
        run: |
          kustomize edit set image frontend=$ECR_REPO:${{ github.sha }}

      - name: Deploy to Kubernetes
        working-directory: starter/frontend/k8s
        run: |
          kustomize build | kubectl apply -f -